#include "dllstub_def.h"

static const char DLL_NAME[] = "dwmapi.nt.dll";

DEFINE_FUNC0(DllCanUnloadNow)
DEFINE_FUNC3(DllGetClassObject)
DEFINE_FUNC1(DwmAttachMilContent)
DEFINE_FUNC5(DwmDefWindowProc)
DEFINE_FUNC1(DwmDetachMilContent)
DEFINE_FUNC2(DwmEnableBlurBehindWindow)
DEFINE_FUNC1(DwmEnableComposition)
DEFINE_FUNC1(DwmEnableMMCSS)
DEFINE_FUNC2(DwmExtendFrameIntoClientArea)
DEFINE_FUNC0(DwmFlush)
DEFINE_FUNC2(DwmGetColorizationColor)
DEFINE_FUNC2(DwmGetCompositionTimingInfo)
DEFINE_FUNC2(DwmGetGraphicsStreamClient)
DEFINE_FUNC2(DwmGetGraphicsStreamTransformHint)
DEFINE_FUNC3(DwmGetTransportAttributes)
DEFINE_FUNC2(DwmGetUnmetTabRequirements)
DEFINE_FUNC4(DwmGetWindowAttribute)
DEFINE_FUNC1(DwmInvalidateIconicBitmaps)
DEFINE_FUNC1(DwmIsCompositionEnabled)
DEFINE_FUNC3(DwmModifyPreviousDxFrameDuration)
DEFINE_FUNC2(DwmQueryThumbnailSourceSize)
DEFINE_FUNC3(DwmRegisterThumbnail)
DEFINE_FUNC4(DwmRenderGesture)
DEFINE_FUNC2(DwmSetDxFrameDuration)
DEFINE_FUNC4(DwmSetIconicLivePreviewBitmap)
DEFINE_FUNC3(DwmSetIconicThumbnail)
DEFINE_FUNC2(DwmSetPresentParameters)
DEFINE_FUNC4(DwmSetWindowAttribute)
DEFINE_FUNC2(DwmShowContact)
DEFINE_FUNC4(DwmTetherContact)
DEFINE_FUNC5(DwmTetherTextContact)
DEFINE_FUNC2(DwmTransitionOwnedWindow)
DEFINE_FUNC1(DwmUnregisterThumbnail)
DEFINE_FUNC2(DwmUpdateThumbnailProperties)
DEFINE_FUNC2(DwmpAllocateSecurityDescriptor)
DEFINE_FUNC8(DwmpDxGetWindowSharedSurface)
DEFINE_FUNC6(DwmpDxUpdateWindowSharedSurface)
DEFINE_FUNC1(DwmpDxgiIsThreadDesktopComposited)
DEFINE_FUNC0(DwmpEnableDDASupport)
DEFINE_FUNC1(DwmpFreeSecurityDescriptor)
DEFINE_FUNC1(DwmpGetColorizationParameters)
DEFINE_FUNC3(DwmpRenderFlick)
DEFINE_FUNC0(DwmpSetColorizationParameters)
DEFINE_FUNC0(DwmpUpdateProxyWindowForCapture)
